### ISSUE TITLE
The logics about the ESDF update

### ISSUE THREAD

**Issue by hjxwhy** [nvidia-isaac/nvblox#8]
The ESDF update method here https://github.com/nvidia-isaac/nvblox/blob/0f9b8807a1d962247e85ffa607a8d422b00a7545/nvblox/src/integrators/cuda/esdf_integrator.cu#L666 is different from voxblox, also the esdf distance is not given by TSDF distance. What are the reasons for the changes? Is there a paper?

**Comment by helenol** [comment]
Hey @hjxwhy , great question and well-noticed. ;) There's no paper yet, but basically the method in voxblox is not parallelizable while the one in nvblox is (it's a mix of PBA https://www.comp.nus.edu.sg/~tants/pba_files/pba-old.pdf  and the incremental method in voxblox basically). There's 2 key differences in the structure of the problem:
1. voxblox did quasi-Euclidean distance while nvblox does *full* Euclidean distance, lowering the overall error.
2. voxblox used tsdf distance while nvblox (at the moment) treats the tsdf as an occupancy metric. Nothing inherent in the algorithm prevents using true distance, just requires a bit more bookkeeping than I was prepared to do in version 1.

nvblox allows you to use *far* smaller voxels than voxblox since it is ridiculously faster; i.e., you can run everything at 5 cm voxels on a Jetson NX without issue, so I expect the tsdf distance -> occupancy approximation, especially when combined with full Euclidean instead of quasi-Euclidean distances, to make much less of an impact. One thing I want to do is actually quantify the effect of both on the overall error in the ESDF accuracy, but this is on-going work.
